# Generated by Django 5.0.1 on 2024-01-11 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_allformdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllFormData',
        ),
    ]
