# Generated by Django 5.0.1 on 2024-01-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0005_auto_20240111_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountmodel',
            name='Shipping',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amountmodel',
            name='Subtotal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amountmodel',
            name='Taxes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='amountmodel',
            name='Total',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='card',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='cash',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='checks',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='other',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='paypal',
            field=models.BooleanField(),
        ),
    ]
